/**
 * RCAN Message — command envelope for RCAN v1.2.
 *
 * A RCANMessage wraps a robot command with:
 * - RCAN protocol version
 * - Target Robot URI
 * - Command name and parameters
 * - Optional AI confidence score (§16)
 * - Optional model identity (§16)
 * - Optional Ed25519 signature
 */

import { RobotURI } from "./address";

export interface SignatureBlock {
  alg: string;
  kid: string;
  sig: string;
}

export interface RCANMessageData {
  rcan?: string;
  cmd: string;
  target: string | RobotURI;
  params?: Record<string, unknown>;
  confidence?: number;
  modelIdentity?: string;
  model_identity?: string; // snake_case alias
  signature?: SignatureBlock;
  timestamp?: string;
  [key: string]: unknown;
}

export class RCANMessageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RCANMessageError";
  }
}

export class RCANMessage {
  readonly rcan: string;
  readonly cmd: string;
  readonly target: string;
  readonly params: Record<string, unknown>;
  readonly confidence: number | undefined;
  readonly modelIdentity: string | undefined;
  readonly signature: SignatureBlock | undefined;
  readonly timestamp: string;

  constructor(data: RCANMessageData) {
    if (!data.cmd || data.cmd.trim() === "") {
      throw new RCANMessageError("'cmd' is required");
    }
    if (!data.target) {
      throw new RCANMessageError("'target' is required");
    }

    this.rcan = data.rcan ?? "1.2";
    this.cmd = data.cmd;
    this.target =
      data.target instanceof RobotURI ? data.target.toString() : String(data.target);
    this.params = data.params ?? {};
    this.confidence = data.confidence;
    this.modelIdentity = data.modelIdentity ?? data.model_identity;
    this.signature = data.signature;
    this.timestamp = data.timestamp ?? new Date().toISOString();

    if (this.confidence !== undefined) {
      if (this.confidence < 0 || this.confidence > 1) {
        throw new RCANMessageError(
          `confidence must be in [0.0, 1.0] — got ${this.confidence}`
        );
      }
    }
  }

  /** Whether this message has a signature block */
  get isSigned(): boolean {
    return this.signature !== undefined && this.signature.sig !== "";
  }

  /** Whether this message was generated by an AI model (has confidence score) */
  get isAiDriven(): boolean {
    return this.confidence !== undefined;
  }

  /** Serialize to a plain object */
  toJSON(): Record<string, unknown> {
    const obj: Record<string, unknown> = {
      rcan: this.rcan,
      cmd: this.cmd,
      target: this.target,
      timestamp: this.timestamp,
    };
    if (Object.keys(this.params).length > 0) obj.params = this.params;
    if (this.confidence !== undefined) obj.confidence = this.confidence;
    if (this.modelIdentity) obj.model_identity = this.modelIdentity;
    if (this.signature) obj.signature = this.signature;
    return obj;
  }

  /** Serialize to JSON string */
  toJSONString(indent?: number): string {
    return JSON.stringify(this.toJSON(), null, indent);
  }

  /** Parse from a plain object or JSON string */
  static fromJSON(data: string | Record<string, unknown>): RCANMessage {
    let obj: Record<string, unknown>;
    if (typeof data === "string") {
      try {
        obj = JSON.parse(data) as Record<string, unknown>;
      } catch {
        throw new RCANMessageError("Invalid JSON string");
      }
    } else {
      obj = data;
    }

    if (!obj.cmd) throw new RCANMessageError("Missing required field: 'cmd'");
    if (!obj.target) throw new RCANMessageError("Missing required field: 'target'");
    if (!obj.rcan) throw new RCANMessageError("Missing required field: 'rcan'");

    return new RCANMessage({
      rcan: obj.rcan as string,
      cmd: obj.cmd as string,
      target: obj.target as string,
      params: (obj.params as Record<string, unknown>) ?? {},
      confidence: obj.confidence as number | undefined,
      modelIdentity:
        (obj.model_identity as string | undefined) ??
        (obj.modelIdentity as string | undefined),
      signature: obj.signature as SignatureBlock | undefined,
      timestamp: obj.timestamp as string | undefined,
    });
  }
}
